#!/usr/bin/env python3

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Tuple


@dataclass(frozen=True)
class SummaryRow:
    cda: float
    cda_unc: float
    cr: float
    cr_unc: float


def _read_csv_rows(path: Path) -> Iterable[dict]:
    with path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            yield row


def _load_a1_a2_summary(path: Path) -> Dict[str, SummaryRow]:
    out: Dict[str, SummaryRow] = {}
    for row in _read_csv_rows(path):
        config = row["config"]
        out[config] = SummaryRow(
            cda=float(row["CdA_m2_mean"]),
            cda_unc=float(row["CdA_m2_std"]),
            cr=float(row["Cr_mean"]),
            cr_unc=float(row["Cr_std"]),
        )
    return out


def _load_a3_pooled(path: Path, boot_unc: Dict[str, SummaryRow]) -> Dict[str, SummaryRow]:
    out: Dict[str, SummaryRow] = {}
    for row in _read_csv_rows(path):
        config = row["config"]
        if config not in boot_unc:
            raise KeyError(f"Missing bootstrap uncertainty for config '{config}'")
        unc = boot_unc[config]
        out[config] = SummaryRow(
            cda=float(row["CdA_m2"]),
            cda_unc=unc.cda_unc,
            cr=float(row["Cr"]),
            cr_unc=unc.cr_unc,
        )
    return out


def _load_bootstrap_uncertainty(path: Path, model: str = "baseline") -> Dict[str, SummaryRow]:
    out: Dict[str, SummaryRow] = {}
    for row in _read_csv_rows(path):
        if row.get("model") != model:
            continue
        config = row["config"]
        out[config] = SummaryRow(
            cda=float(row["CdA_m2_boot_mean"]),
            cda_unc=float(row["CdA_m2_boot_std"]),
            cr=float(row["Cr_boot_mean"]),
            cr_unc=float(row["Cr_boot_std"]),
        )
    return out


def _fmt_pm(value: float, unc: float, decimals: int) -> str:
    value_s = f"{value:.{decimals}f}"
    unc_s = f"{unc:.{decimals}f}"
    return f"${value_s} \\pm {unc_s}$"


def _escape_latex_text(s: str) -> str:
    # Minimal escaping for use inside \texttt{...}.
    # (Mostly needed for underscores in config names.)
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "#": r"\#",
        "$": r"\$",
        "%": r"\%",
        "&": r"\&",
        "_": r"\_",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in s)


def _render_tables(
    configs: Iterable[str],
    a1: Dict[str, SummaryRow],
    a2: Dict[str, SummaryRow],
    a3: Dict[str, SummaryRow],
) -> str:
    cda_lines = []
    for cfg in configs:
        cfg_tex = _escape_latex_text(cfg)
        cda_lines.append(
            f"\\texttt{{{cfg_tex}}} & {_fmt_pm(a1[cfg].cda, a1[cfg].cda_unc, 3)} & {_fmt_pm(a2[cfg].cda, a2[cfg].cda_unc, 3)} & {_fmt_pm(a3[cfg].cda, a3[cfg].cda_unc, 3)} \\\\"  # noqa: E501
        )

    cr_lines = []
    for cfg in configs:
        cfg_tex = _escape_latex_text(cfg)
        cr_lines.append(
            f"\\texttt{{{cfg_tex}}} & {_fmt_pm(a1[cfg].cr, a1[cfg].cr_unc, 4)} & {_fmt_pm(a2[cfg].cr, a2[cfg].cr_unc, 4)} & {_fmt_pm(a3[cfg].cr, a3[cfg].cr_unc, 4)} \\\\"  # noqa: E501
        )

    # Keep captions/labels in the generated file so the main .tex stays clean.
    rendered = "\n".join(
        [
            "% AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
            "% Generated by Docs/scripts/generate_drag_report_tables.py.",
            "",
            "% Baseline model results (Approaches 1--3)",
            "\\paragraph{Overview: \\(C_dA\\)}",
            "\\begin{table}[h]",
            "\\centering",
            "\\small",
            "\\caption{Baseline model: \\(C_dA\\) per configuration across Approaches 1--3 (mean/pooled value $\\pm$ uncertainty).}",
            "\\label{tab:baseline-cda}",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Config & A1 (per-run) & A2 (paired) & A3 (pooled) \\\\",
            "\\midrule",
            *cda_lines,
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "\\paragraph{Overview: \\(C_r\\)}",
            "\\begin{table}[h]",
            "\\centering",
            "\\small",
            "\\caption{Baseline model: \\(C_r\\) per configuration across Approaches 1--3 (mean/pooled value $\\pm$ uncertainty).}",
            "\\label{tab:baseline-cr}",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Config & A1 (per-run) & A2 (paired) & A3 (pooled) \\\\",
            "\\midrule",
            *cr_lines,
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )

    return rendered


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent.parent

    a1_path = repo_root / "Outputs/03_Drag_Calculation/Approach1_PerRun/csv/drag_config_summary.csv"
    a2_path = repo_root / "Outputs/03_Drag_Calculation/Approach2_PairedOpposites/csv/drag_config_summary.csv"
    a3_path = repo_root / "Outputs/03_Drag_Calculation/Approach3_PooledByConfig/csv/drag_config_pooled_fits.csv"
    boot_path = repo_root / "Outputs/03_Drag_Calculation/bootstrap_pooled_uncertainty.csv"

    missing = [p for p in [a1_path, a2_path, a3_path, boot_path] if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required output CSV(s):\n" + "\n".join(str(p) for p in missing)
        )

    a1 = _load_a1_a2_summary(a1_path)
    a2 = _load_a1_a2_summary(a2_path)
    boot = _load_bootstrap_uncertainty(boot_path, model="baseline")
    a3 = _load_a3_pooled(a3_path, boot_unc=boot)

    # Stable config order (matches main report tables)
    configs = ["full", "no_rear", "no_front_rear", "no_front"]
    for cfg in configs:
        for name, mapping in [("A1", a1), ("A2", a2), ("A3", a3)]:
            if cfg not in mapping:
                raise KeyError(f"Missing config '{cfg}' in {name} inputs")

    out_dir = repo_root / "Docs/03_Drag_Calculation/generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "baseline_results_tables.tex"
    out_path.write_text(_render_tables(configs, a1=a1, a2=a2, a3=a3), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
